### ISSUE TITLE
为什么使用了两次sigmoid?

### ISSUE THREAD

**Issue by LarT2P** [wlguan/DHSNet-PyTorch#3]
首先表示感谢, 代码很直观, 但是有个小问题想请教下:

https://github.com/GuanWenlong/DHSNet-PyTorch/blob/98dff839b94a4968c9b357df68902f05db084c4b/main.py#L117

在网络的前向输出后, 本已有一个sigmoid,这里为什么还需再来一个呢?

**Comment by wlguan** [comment]
这是个错误@LarT2P  多谢指出
